### ISSUE TITLE
New versioning Scheme

### ISSUE THREAD

**Issue by julienmoumne** [piwik/piwik-dotnet-tracker#22]
Before June 2014, [piwik-php-tracker](https://github.com/piwik/piwik-php-tracker) was part of Piwik's code base and therefore followed Piwik's versioning scheme. When it became a separate project, version number went from v2.x.x to v1.0.0.

[piwik-dotnet-tracker](https://github.com/piwik/piwik-dotnet-tracker) was a separate project from the beginning but followed the versioning scheme of Piwik and its tracker. This made bookkeeping convenient when porting the code base from PHP to .NET.

Current version of [piwik-dotnet-tracker](https://github.com/piwik/piwik-dotnet-tracker) 2.16.0 does not correspond to either versions of Piwik and piwik-php-tracker.

piwik-dotnet-tracker should have its own version scheme since:
- following Piwik's versioning scheme does not make sense anymore
- following piwik-php-tracker's scheme would make it hard to merge pull requests for features unique to piwik-dotnet-tracker or submitted in a different order

piwik-dotnet-tracker would benefit from semantic versioning and autogenerated changelogs with, for example, [skywinder/github-changelog-generator](https://github.com/skywinder/github-changelog-generator).

Main issues to address: 
- determining the next version
- dealing with the fact piwik-dotnet-tracker is a publicly published project on [Nuget](https://www.nuget.org/packages/Piwik.Tracker/)
- dealing with the existing [git tags](https://github.com/piwik/piwik-dotnet-tracker/releases)

**Comment by tsteur** [comment]
> Determining the next version:

I'd suggest to follow http://semver.org/ which also helps on deciding to determine the next version

> Current version of piwik-dotnet-tracker 2.16.0 does not correspond to either versions of Piwik and piwik-php-tracker.

I would mention in the README that the version is not related to the Piwik version

In general: The version scheme for this should be independent from any other tracker and Piwik

**Comment by julienmoumne** [comment]
Thanks for the feedback.

Do you also imply it is acceptable to start from v2.16.0 instead of finding a way to somehow reset at v1.0.0?

**Comment by tsteur** [comment]
I would probably start from 2.16.0 as it would be otherwise confusing when having already released a 2.X version for this tracker.

**Comment by mattab** [comment]
Sounds good to use 2.16.0 

The new C# SDK was advertised in the 2.16.2 blog post: https://piwik.org/changelog/piwik-2-16-2/ and on social network eg. https://twitter.com/piwik/status/762498653327990787

**Comment by julienmoumne** [comment]
See [a draft of the changelog](https://github.com/piwik/piwik-dotnet-tracker/blob/1560ed7bea2df9722abd220ced8d5f0ad84e405e/CHANGELOG.md)

**Comment by julienmoumne** [comment]
New version will be 3.0.0 since the public API changed.
