### ISSUE TITLE
Remove unused "data" request parameter

### ISSUE THREAD

**Issue by julienmoumne** [piwik/piwik-dotnet-tracker#38]
Mentioned by @ptr1120 in https://github.com/piwik/piwik-dotnet-tracker/pull/36.

We should provide a way to set the value.

**Comment by mattab** [comment]
As you have already implemented `setCustomTrackingParameter` in the C# sdk, it should be possible to use this method to define a custom `data` parameter. Since `data` is not a supported tracking api parameter, maybe this is not really needed?

**Comment by julienmoumne** [comment]
Fixed in https://github.com/piwik/piwik-dotnet-tracker/commit/642061fe890833c6b0407a7e74e3caf590ae1957
