### ISSUE TITLE
License not for commercial use

### ISSUE THREAD

**Issue by JFMG** [piwik/piwik-dotnet-tracker#43]
Is it intended that this project uses a GPL license? The disadvantage of the GPL license is that it permits commercial use. Therefore most NuGet packages are using the MIT license. The MIT license is very simple. It can be found here: https://opensource.org/licenses/MIT

Is it possible to change this projects license to the MIT license?

**Comment by JFMG** [comment]
Sorry, I've just seen that there is already an open issue for that: #23 

As discussed in #23 can you now please change the license to the BSD license?

**Comment by mattab** [comment]
Yes, License should be changed next week when Julien will be back

**Comment by JFMG** [comment]
Awesome! Thank you! 😄

**Comment by julienmoumne** [comment]
fixed in 4883823b5ba5f1a482adb313988ce0456103bc00
