### ISSUE TITLE
Add NuGet support

### ISSUE THREAD

**Issue by tetsuo13** [piwik/piwik-dotnet-tracker#8]
Please add an official NuGet package for this project.

**Comment by apopovic** [comment]
I would also like an official NuGet packages for this project.

**Comment by JulienMoumne** [comment]
Would you have any suggestions on how this could be automated?

The idea would be to trigger a 'nuget push' each time a git tag is created.

Once #7 is completed, it would be good to conditionally run 'nuget push' only if all tests are green.

Piwik relies on travis-ci for such tasks. For simplicity, It would be nice to use the same tool.

**Comment by tetsuo13** [comment]
I've started working on adding NuGet support. It'll use the `AssemblyVersion` attribute to set the version of the NuGet package, so that'll need to start being used and maintained. I don't think it'll be possible to have the NuGet package versions reflect all of the tags in the repo since you can't have letters in it -- they must follow the "major.minor.revision.build" format. It may follow that only non-beta tags of this repo would be packaged and pushed.

I've added two batch scripts to handle building and pushing the package as well. Create a Release build of the solution and run `nuget_pack.bat` to create a NuGet package file. Use `nuget_push.bat` to publish the package. You'll need to configure an API key before publishing however. You can run

```
nuget.exe setApiKey Your-API-Key
```

to set the API key to use when publishing.

I attempted to learn Travis CI enough to try to iron out how to tie the NuGet publish with a successful unit test run in a build but couldn't get the whole thing working well enough. Even though Travis CI's [documentation states that it can build a C# project](http://docs.travis-ci.com/user/languages/csharp/), I couldn't get this to work.

Using the basic `.travis.yml` for a C# project as noted in their doc:

```yml
language: csharp
solution: solution-name.sln
```

their [https://lint.travis-ci.org/](Travis WebLint) site gave the following errors:

    in language section: illegal value csharp, defaulting to ruby
    unexpected key solution, dropping

Indeed when I ran the build the output window ran with Ruby and failed miserably. It would seem that I was hit by travis-ci/travis-yaml#35 so I took another approach and followed some examples found on GitHub that used Mono on Mac by specifying Objective-C as the language and also Mono on Linux using C but all failed to work quite right. I can provide more detail from my trials if it would help.

**Comment by JulienMoumne** [comment]
Thank you for this contribution!

I would like to add a section in the README explaining **when** and **how** the project should be published.

Can you confirm the following steps are correct and complete ?
## Publishing the project to NuGet

### Requirements
  1. The process detailed in this section must be executed right before adding a release tag to git
  2. Publishing the project to NuGet must be done by a member of the Piwik team, holder of the private NuGet Key

### Steps
1. Validate tests (requires #7)
2. Update and commit AssemblyInfo.cs with new version
3. Create git tag
4. Build the project using nuget_pack.bat
5. Publish the project using nuget_push.bat

Cheers

**Comment by JulienMoumne** [comment]
Also, could your commit be easily extended to publish the source code as well as the binaries?

**Comment by tetsuo13** [comment]
I've modified `nuget_pack.bat` to also build a symbols package. You will need to register an account at [SymbolSource](https://www.symbolsource.org/Public) so that the the symbols package is automatically registered there when running `nuget_push.bat` (it'll upload both packages). Perhaps this can be added to #9.

I haven't tested running `nuget_push.bat` along with the newly added symbols package.

For the "Publishing the project to NuGet" documentation block, the steps section might need some clarification on exactly when the project is built versus packed since `nuget_pack.bat` doesn't initiate a build. Perhaps something like this:

1. Validate tests (requires #7)
2. Update and commit `AssemblyInfo.cs` with new version
3. Create git tag
4. Build the project using the Release solution configuration
5. Create NuGet package using `nuget_pack.bat`
6. Publish the package using `nuget_push.bat`

**Comment by tetsuo13** [comment]
Also, is there an image that can be linked to for the NuGet package? This image would show when viewing the package at NuGet.org as well as within Visual Studio. Needs to be a 32x32 PNG with transparent background. I tried searching through Piwik's web site but couldn't find anything suitable. Something like https://raw.githubusercontent.com/piwik/piwik/f5cc9083203d8bedd3ada20acb6d44a000ae1754/plugins/Morpheus/images/logo.png tweaked to the right dimensions might work.

**Comment by JulienMoumne** [comment]
Thanks a bunch.

I've asked the team for the logo.

**Comment by JulienMoumne** [comment]
Should the logo be committed to git or should it be submitted while creating the nuget account?

Also, could you create a pull request for your work?

**Comment by JulienMoumne** [comment]
Here is the logo : http://postimg.org/image/lgb4nosft/

**Comment by JulienMoumne** [comment]
I will close both this issue and issue #9 when releasing version 2.0.

**Comment by JulienMoumne** [comment]
Note to self : 
 - remove nuget.exe from git and update script files (nuget.exe should be manually installed and configured in the path)
 - move scripts and image to subdirectories
 - update doc to reflect these changes

**Comment by JulienMoumne** [comment]
When publishing symbols, I get the following error : 

`Failed to process request. 'Package submission failed: Server was unable to proc
ess request. ---> ComponentActivator: could not instantiate SymbolSource.Process
ing.Tools.PdbSourceExtractor ---> Exception has been thrown by the target of an
invocation. ---> Value cannot be null. Parameter name: path1. See http://www.sym
bolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing
 this error if your client discards attached detailed information.'.
The remote server returned an error: (506) Package submission failed: Server was
 unable to process request. ---> ComponentActivator: could not instantiate Symbo
lSource.Processing.Tools.PdbSourceExtractor ---> Exception has been thrown by th
e target of an invocation. ---> Value cannot be null. Parameter name: path1. See
 http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may
help diagnosing this error if your client discards attached detailed information
...`

Would you have any idea how I could troubleshoot this?

**Comment by JulienMoumne** [comment]
Lets resolve the symbols issue in #13
